version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/app
    networks:
      - nginx-proxy
      - default
    volumes:
      - .:/var/www/app
    ports:
      - 8042:8080

  nginx:
    image: nginx:1.9
    restart: always
    tty: true
    depends_on:
      - app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-proxy
      - default
networks:
  nginx-proxy:
