version: '3.5'

services:
  php:
    build:
      context: .
      dockerfile: docker/PHPDockerfile
    restart: always
  app:
    build:
      context: .
      dockerfile: docker/AppDockerfile
    restart: always
    tty: true
    depends_on:
      - php
    ports:
      - "8081:80"